version: "3.8"

services:
  jupyter:
    build: jupyter
    depends_on:
      - spark-master
    ports:
      - 8888:8888
    volumes:
      - type: bind
        source: ./jupyter/notebooks
        target: /home/jovyan/notebooks
      - type: bind
        source: ./data
        target: /home/jovyan/data
      - type: bind
        source: ./jupyter/src
        target: /home/jovyan/src
    env_file:
      - .env
      - ./jupyter/.env
    environment:
      - JUPYTER_ENABLE_LAB=yes
  spark:
    image: docker.io/bitnami/spark:3
    depends_on:
      - spark-worker
    environment:
      - SPARK_MODE=master
    env_file:
      - .env
    ports:
      - 8080:8080
      - 7077:7077
      - 4040:4040
    volumes:
      - type: bind
        source: ./data
        target: /data
  spark-worker:
    image: docker.io/bitnami/spark:3
    env_file:
      - .env
    ports:
      - 8081:8081
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
  get_data:
    image: curlimages/curl
    volumes:
      - type: bind
        source: ./data
        target: /data
    command: > 
      sh -c "curl http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data > /data/iris.csv &&
             curl https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv > ./data/titanic.csv"
